participants:
  - el_type: geth
    el_image: ethereum/client-go:v1.14.12
    cl_type: lighthouse
    cl_image: sigp/lighthouse:v5.3.0
  - el_type: geth
    el_image: ethereum/client-go:v1.14.12
    cl_type: lambda
    cl_image: lambda_ethereum_consensus:latest
    use_separate_vc: false
    count: 1
    cl_max_mem: 4096
    keymanager_enabled: true
additional_services: []
#   - assertoor
# assertoor_params:
#   run_stability_check: false
#   run_block_proposal_check: false
#   run_transaction_test: false
#   run_blob_transaction_test: false
#   run_opcodes_transaction_test: false
#   run_lifecycle_test: false
#   test: []
