participants:
  - el_type: nethermind
    cl_type: prysm
  - el_type: reth
    cl_type: lighthouse
  - el_type: geth
    cl_type: lambda
    cl_image: lambda_ethereum_consensus:latest
    use_separate_vc: false
    count: 1
    cl_max_mem: 4096
    keymanager_enabled: true
additional_services: []
#   - assertoor
# assertoor_params:
#   run_stability_check: false
#   run_block_proposal_check: false
#   run_transaction_test: false
#   run_blob_transaction_test: false
#   run_opcodes_transaction_test: false
#   run_lifecycle_test: false
#   test: []
