participants:
  - el_type: geth
    cl_type: teku
  - el_type: nethermind
    cl_type: prysm
  - el_type: erigon
    cl_type: nimbus
  - el_type: besu
    cl_type: lighthouse
  - el_type: geth
    cl_type: lambda
    cl_image: lambda_ethereum_consensus:latest
    use_separate_vc: false
    count: 1
    validator_count: 32
    cl_max_mem: 4096
    keymanager_enabled: true
  - el_type: reth
    cl_type: lodestar
additional_services:
  - assertoor
assertoor_params:
  run_stability_check: true
  run_block_proposal_check: false