participants:
  - el_type: geth
    cl_type: teku
  - el_type: nethermind
    cl_type: prysm
  - el_type: erigon
    cl_type: nimbus
  - el_type: besu
    cl_type: lighthouse
  - el_type: reth
    cl_type: lodestar
  - el_type: geth
    cl_type: lambda
    cl_image: lambda_ethereum_consensus:latest
additional_services:
  - assertoor
assertoor_params:
  run_stability_check: true
  run_block_proposal_check: false