global:
  scrape_interval: 1s

scrape_configs:
  - job_name: "telemetry_metrics_prometheus"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["host.docker.internal:9568"]
  - job_name: "prometheus_ex"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["host.docker.internal:4000"]
