{
 "title": "Node",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "lambda_ethereum_consensus_prom_ex_beam_stats_uptime_milliseconds_count{job=\"prom_ex\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Store Slot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sync_store_slot{}", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Head Slot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sync_on_block_slot{}", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "peerbook_peers_count", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "DB Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "db_size_total", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Current sync progress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "targets": [
    { "expr": "sync_store_slot{}", "legendFormat": "max_slot" },
    { "expr": "sync_on_block_slot{}", "legendFormat": "processed_slot" }
   ]
  },
  {
   "title": "Message queue length",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(vm_message_queue_length{process!~\"LambdaEthereumConsensus.ForkChoice|LambdaEthereumConsensus.Beacon.PendingBlocks\"})",
     "legendFormat": "total_message_queue_length"
    },
    {
     "expr": "vm_message_queue_length{process=\"LambdaEthereumConsensus.ForkChoice\"}",
     "legendFormat": "{{process}}"
    },
    {
     "expr": "vm_message_queue_length{process=\"LambdaEthereumConsensus.Beacon.PendingBlocks\"}",
     "legendFormat": "{{process}}"
    }
   ]
  },
  {
   "title": "Block Processing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block processing time",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(increase(sync_on_block_stop_duration_bucket[$__interval])) by (le)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "First level handler block processing times",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fork_choice_latency_stop_duration{transition=\"\"}",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Fork choice handler times",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "fork_choice_latency_stop_duration{handler=\"on_block\", transition!=\"\"}",
       "legendFormat": "{{handler}} - {{transition}} - {{operation}}"
      },
      {
       "expr": "fork_choice_recompute_head_stop_duration",
       "legendFormat": "recompute_head"
      },
      {
       "expr": "fork_choice_latency_stop_duration{handler!=\"on_block\"}",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Blockchain View",
     "type": "nodeGraph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      { "expr": "blocks_status_total", "legendFormat": "__auto" },
      { "expr": "blocks_relationship_total", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "P2P Networking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "P2P Requests",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "rate(network_request_count{result=\"success\"}[$__rate_interval])",
       "legendFormat": "success"
      },
      {
       "expr": "sum(rate(network_request_count{result=~\"error|retry\"}[$__rate_interval]))",
       "legendFormat": "error"
      }
     ]
    },
    {
     "title": "Peer additions",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "rate(peers_connection_count{result=\"success\"}[$__rate_interval])",
       "legendFormat": "added"
      },
      {
       "expr": "sum(rate(peers_challenge_count{result=\"failed\"}[$__rate_interval])) + sum(rate(network_request_count{result=~\"error|retry\"}[$__rate_interval]))",
       "legendFormat": "removed"
      }
     ]
    },
    {
     "title": "Peer challenges",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "rate(peers_challenge_count{result=\"failed\"}[$__rate_interval])",
       "legendFormat": "failed"
      },
      {
       "expr": "rate(peers_challenge_count{result=\"passed\"}[$__rate_interval])",
       "legendFormat": "passed"
      }
     ]
    },
    {
     "title": "Peers (Gossip)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 34 },
     "targets": [
      { "expr": "peerbook_peers_count", "legendFormat": "current_peer_amount" }
     ]
    },
    {
     "title": "Block download rate",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(network_request_blocks{}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Error reasons",
     "type": "piechart",
     "gridPos": { "h": 6, "w": 7, "x": 5, "y": 40 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by(reason) (network_request_count{result=~\"error|retry\",type=\"by_root\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Libp2pPort Messages",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
     "targets": [
      {
       "expr": "sum by (direction) (rate(port_message_count{direction=\"->elixir\"}[$__rate_interval]))",
       "legendFormat": "incoming"
      },
      {
       "expr": "sum by (direction) (rate(port_message_count{direction=\"elixir->\"}[$__rate_interval]))",
       "legendFormat": "outgoing"
      },
      {
       "expr": "sum by () (rate(port_message_count{}[$__rate_interval]))",
       "legendFormat": "total"
      },
      {
       "expr": "rate(port_message_count{}[$__rate_interval])",
       "legendFormat": "{{function}}"
      }
     ]
    }
   ]
  },
  {
   "title": "GossipSub",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "PubSub topics joined",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
     "targets": [
      {
       "expr": "network_pubsub_topic_active_active",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Grafted",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
     "targets": [
      {
       "expr": "network_pubsub_topics_graft_count{} - network_pubsub_topics_prune_count{}",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Deliver Messages",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "rate(network_pubsub_topics_deliver_message_count{}[$__rate_interval])",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Validate Messages",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
     "targets": [
      {
       "expr": "rate(network_pubsub_topics_validate_message_count{}[$__rate_interval])",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Duplicate Messages",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "rate(network_pubsub_topics_duplicate_message_count{}[$__rate_interval])",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Undeliverable Messages",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 59 },
     "targets": [
      {
       "expr": "rate(network_pubsub_topics_un_deliverable_message_count{}[$__rate_interval])",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Reject Messages",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 65 },
     "targets": [
      {
       "expr": "rate(network_pubsub_topics_reject_message_count{}[$__rate_interval])",
       "legendFormat": "{{topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Libp2p Port",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 },
   "collapsed": true,
   "panels": [
    {
     "title": "Libp2pPort Handlers Count",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "libp2pport_handler_stop_count", "legendFormat": "{{module}} - {{action}}" }
     ]
    },
    {
     "title": "Libp2pPort Handlers Time",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "libp2pport_handler_stop_duration",
       "legendFormat": "{{module}} - {{action}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mean time per db operation",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "db_latency_stop_duration", "legendFormat": "{{module}} - {{action}}" }
     ]
    },
    {
     "title": "Database size",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "db_size_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "SubnetInfo Persisting Duration",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "db_latency_stop_duration{module=\"subnet\", action=\"persist\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "SubnetInfo Fetching Duration",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "db_latency_stop_duration{module=\"subnet\", action=\"fetch\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raw logs",
     "type": "logs",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "{job=\"lambda_ethereum_consensus\"} |= ``",
       "maxLines": 100
      }
     ]
    }
   ]
  }
 ]
}