version: '3'
name: 'lambda-ethereum-consensus-grafana'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    volumes:
      # prometheus configuration
      - ./prometheus:/etc/prometheus
      # prometheus data
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    networks:
      grafana-prometheus:
        aliases:
          - prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      # grafana configuration
      - ./grafana/provisioning:/etc/grafana/provisioning
      # grafana data
      - grafana-data:/var/lib/grafana
    networks:
      grafana-prometheus:
        aliases:
          - grafana
      grafana-loki:
        aliases:
          - grafana

  loki:
    image: grafana/loki
    container_name: loki
    volumes:
      # loki configuration
      - ./loki:/etc/loki
      # loki data
      - loki-data:/var/lib/loki
    command: --config.file=/etc/loki/loki.yml
    networks:
      grafana-loki:
        aliases:
          - loki
      loki-promtail:
        aliases:
          - loki

  promtail:
    image: grafana/promtail
    container_name: promtail
    volumes:
      # promtail configuration
      - ./promtail:/etc/promtail
      # logs to scrape
      - ../logs:/var/log/consensus
      # promtail data
      - promtail-data:/tmp/promtail
    command: --config.file=/etc/promtail/promtail.yml
    networks:
      loki-promtail:
        aliases:
          - promtail

networks:
  grafana-prometheus:
    driver: bridge
  grafana-loki:
    driver: bridge
  loki-promtail:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:
  loki-data:
  promtail-data:
