version: '3'
name: 'lambda-ethereum-consensus-grafana'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-data:/var/lib/grafana

  loki:
    image: grafana/loki
    container_name: loki
    volumes:
      - ./loki:/etc/loki
      - loki-data:/var/lib/loki
    command: --config.file=/etc/loki/loki.yml

  promtail:
    image: grafana/promtail
    container_name: promtail
    volumes:
      - ./promtail:/etc/promtail
      - ../logs:/var/log/consensus
      - promtail-data:/tmp/promtail
    command: --config.file=/etc/promtail/promtail.yml

networks:
  open:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:
  loki-data:
  promtail-data:
